/**
 * DDW AI Hub - 插件市场目录
 * 当前后端暂未提供 marketplace API，这里维护一个静态目录
 * 真实部署时会替换为 /api/v1/marketplace/plugins 接口
 * 字段设计与后端 InstalledPlugin / Plugin Manifest 对齐
 *
 * 共 85 个插件，按 9 大业务域分组：
 * 销售CRM → 质量合规 → 医疗健康 → 财务运营 → 知识培训
 * → 人力行政 → 运营管理 → 平台能力 → 通用
 */
window.DDW_PLUGINS = [

  // ========== 销售CRM ==========
  {
    id: "ddw_commission",
    name: "ddw_commission",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "医生提成核算（基于 ddw_payment 收费数据）",
    description: "医生提成核算（基于 ddw_payment 收费数据）",
    version: "0.1.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_contact_hub",
    name: "ddw-contact-hub",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "企业级联系人主数据管理。姓名、职位、部门、手机、邮箱、微信、标签、分组、主联系人标记；支持按企业聚合…",
    description: "企业级联系人主数据管理。姓名、职位、部门、手机、邮箱、微信、标签、分组、主联系人标记；支持按企业聚合、模糊搜索（autocomplete）、统计概览。删除走硬删除（联系人无重要业务依赖）。",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_followup",
    name: "ddw_followup",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "回访与复诊提醒",
    description: "回访与复诊提醒",
    version: "0.1.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_lead_claim",
    name: "ddw-lead-claim",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售端客户报备与归属保护机制。渠道/销售对客户企业的保护期占位：默认 60 天，自动计算 expir…",
    description: "销售端客户报备与归属保护机制。渠道/销售对客户企业的保护期占位：默认 60 天，自动计算 expire_at；list/get/conflict/stats 等 read 操作前自动标记过期；支持主动",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_opportunity",
    name: "ddw-opportunity",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售商机（Opportunity）全生命周期管理。涵盖阶段流转（初步接触→成交/丢单）、成交概率自动…",
    description: "销售商机（Opportunity）全生命周期管理。涵盖阶段流转（初步接触→成交/丢单）、成交概率自动同步、漏斗统计、概览统计；与企业主体、联系人关联。提供商机列表、详情、阶段更新、成交/丢单标记、统计",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_order",
    name: "ddw-order",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售端订单全生命周期管理。明细用 JSON 列存储（与报价单子表不同的规范选择）；自动生成单号 OR…",
    description: "销售端订单全生命周期管理。明细用 JSON 列存储（与报价单子表不同的规范选择）；自动生成单号 ORD-YYYYMMDD-NNN；自动按 items 计算总金额；状态机 pending→confirm",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理", "状态机"]
  },  {
    id: "ddw_partner_directory",
    name: "ddw-partner-directory",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "经销商/代理商/分销商的开户与档案管理。类型（reseller/agent/distributor）…",
    description: "经销商/代理商/分销商的开户与档案管理。类型（reseller/agent/distributor）、等级（normal/silver/gold/strategic）、区域/行业、三类折扣（产品/插件",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_quotation",
    name: "ddw-quotation",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售端报价单全生命周期管理。主表 + 明细子表结构；自动生成单号 QT-YYYYMMDD-NNN；自…",
    description: "销售端报价单全生命周期管理。主表 + 明细子表结构；自动生成单号 QT-YYYYMMDD-NNN；自动计算总金额与折后金额；状态机 draft→sent→accepted/rejected/expir",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理", "状态机"]
  },  {
    id: "ddw_receivable",
    name: "ddw-receivable",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售端应收（Receivable）全生命周期管理。应收节点（首款/部署款/验收款/续费款）、部分收款…",
    description: "销售端应收（Receivable）全生命周期管理。应收节点（首款/部署款/验收款/续费款）、部分收款与全额收款、逾期自动标记、统计概览（应收 / 已收 / 未收 / 逾期）。与企业/订单/合同可选关联",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_renewal",
    name: "ddw-renewal",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售端 CRM 续费管理插件。跨插件查询 crm_licenses 与 crm_contracts，…",
    description: "销售端 CRM 续费管理插件。跨插件查询 crm_licenses 与 crm_contracts，提供即将到期（30/60/90天）/已逾期许可证清单、续费报价估算、续费率统计等指标。",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_sales_copilot",
    name: "ddw-sales-copilot",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售端 CRM AI 能力插件。聚合 P0-1~P3-3 的数据，提供商机阶段建议、客户风险提示、行…",
    description: "销售端 CRM AI 能力插件。聚合 P0-1~P3-3 的数据，提供商机阶段建议、客户风险提示、行动建议、销售日报/周报生成。AI 推理走平台 embedded_llm，不创建任何新表。",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理", "AI能力"]
  },  {
    id: "ddw_sales_dashboard",
    name: "ddw-sales-dashboard",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售端 CRM 聚合查询插件。基于 P0-1~P0-4 插件的数据，提供销售仪表盘所需的统计指标：总…",
    description: "销售端 CRM 聚合查询插件。基于 P0-1~P0-4 插件的数据，提供销售仪表盘所需的统计指标：总览、漏斗、趋势、销售排行、最近商机、阶段分布。",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理"]
  },  {
    id: "ddw_sales_note",
    name: "ddw-sales-note",
    domain: "销售CRM",
    category: "通用",
    icon: "💼",
    tagline: "销售端拜访/电话/会议/微信/邮件沟通记录管理。支持按商机/联系人/客户/记录人/类型/时间多维检索…",
    description: "销售端拜访/电话/会议/微信/邮件沟通记录管理。支持按商机/联系人/客户/记录人/类型/时间多维检索与统计。",
    version: "1.0.0",
    installed: false,
    tags: ["CRM", "销售管理", "智能检索"]
  },
  // ========== 质量合规 ==========
  {
    id: "ddw_esg_assessment",
    name: "ddw-esg-assessment",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "ESG assessment engine with scoring, skip logic, be…",
    description: "ESG assessment engine with scoring, skip logic, benchmarking, and multi-framework support",
    version: "1.0.0",
    installed: false,
    tags: ["合规", "质量管理"]
  },  {
    id: "ddw_esg_chatbot",
    name: "ddw-esg-chatbot",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "ESG AI customer service chatbot with RAG pipeline,…",
    description: "ESG AI customer service chatbot with RAG pipeline, conversation management, and human escalation",
    version: "1.0.0",
    installed: false,
    tags: ["合规", "质量管理", "AI能力", "智能检索"]
  },  {
    id: "ddw_esg_knowledge",
    name: "ddw-esg-knowledge",
    domain: "质量合规",
    category: "esg",
    icon: "🛡️",
    tagline: "ESG Knowledge Base Plugin - Document management, f…",
    description: "ESG Knowledge Base Plugin - Document management, full-text search, semantic search, and RAG retrieva",
    version: "1.0.0",
    installed: false,
    tags: ["合规", "质量管理", "智能检索"]
  },  {
    id: "ddw_esg_payment",
    name: "ddw-esg-payment",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "ESG payment processing with order management, prom…",
    description: "ESG payment processing with order management, promotion/commission system, and payment gateway frame",
    version: "0.1.0",
    installed: false,
    tags: ["合规", "质量管理"]
  },  {
    id: "ddw_esg_question_bank",
    name: "ddw-esg-question-bank",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "ESG question bank engine — 12 frameworks (ISO14001…",
    description: "ESG question bank engine — 12 frameworks (ISO14001, ISO45001, GRI, CDP, SASB, TCFD, GB/T36000, GB/T2",
    version: "1.0.0",
    installed: false,
    tags: ["合规", "质量管理"]
  },  {
    id: "ddw_esg_report",
    name: "ddw-esg-report",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "ESG assessment report generator — produces PDF rep…",
    description: "ESG assessment report generator — produces PDF reports with radar charts, score tables, meta analysi",
    version: "0.1.0",
    installed: false,
    tags: ["合规", "质量管理"]
  },  {
    id: "ddw_quality_assistant",
    name: "ddw-quality-assistant",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "DDW 质量小助手 — 8D/CAPA/偏差/投诉回复/5Why AI辅助生成",
    description: "DDW 质量小助手 — 8D/CAPA/偏差/投诉回复/5Why AI辅助生成",
    version: "1.0.0",
    installed: false,
    tags: ["合规", "质量管理", "AI能力"]
  },  {
    id: "ddw_quality_knowledge",
    name: "ddw-quality-knowledge",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "DDW 质量知识检索 — ISO22000/FSSC22000/HACCP/SOP/历史案例/法规条…",
    description: "DDW 质量知识检索 — ISO22000/FSSC22000/HACCP/SOP/历史案例/法规条款智能检索",
    version: "1.0.0",
    installed: false,
    tags: ["合规", "质量管理", "智能检索"]
  },  {
    id: "ddw_regulatory_evidence",
    name: "ddw-regulatory-evidence",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "DDW 法规证据索引 — NHC/EU Novel Food/EFSA/FDA法规条款检索与证据链管…",
    description: "DDW 法规证据索引 — NHC/EU Novel Food/EFSA/FDA法规条款检索与证据链管理",
    version: "1.0.0",
    installed: false,
    tags: ["合规", "质量管理", "智能检索"]
  },  {
    id: "ddw_spc_basic",
    name: "ddw-spc-basic",
    domain: "质量合规",
    category: "通用",
    icon: "🛡️",
    tagline: "DDW SPC基础 — 控制图/Cp/Cpk/Ppk/判异规则/过程能力分析",
    description: "DDW SPC基础 — 控制图/Cp/Cpk/Ppk/判异规则/过程能力分析",
    version: "1.0.0",
    installed: false,
    tags: ["合规", "质量管理"]
  },
  // ========== 医疗健康 ==========
  {
    id: "ddw_clinic_cs",
    name: "ddw_clinic_cs",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "口腔诊所 AI 客服（行业细分第一站）— 武汉东华口腔青山店。 患者咨询/预约引导/应急指导/术后关…",
    description: "口腔诊所 AI 客服（行业细分第一站）— 武汉东华口腔青山店。 患者咨询/预约引导/应急指导/术后关怀，价格红线内置（绝不报价）。 ",
    version: "0.1.0",
    installed: false,
    tags: ["医疗", "AI能力"]
  },  {
    id: "ddw_clinical_asr",
    name: "ddw_clinical_asr",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "LLM 医疗实体抽取（9 类口腔诊疗）",
    description: "LLM 医疗实体抽取（9 类口腔诊疗）",
    version: "0.1.0",
    installed: false,
    tags: ["医疗", "AI能力"]
  },  {
    id: "ddw_dental_emr",
    name: "ddw_dental_emr",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "口腔病历主插件（基于 9 类模板的创建/查询/状态流转）",
    description: "口腔病历主插件（基于 9 类模板的创建/查询/状态流转）",
    version: "0.1.0",
    installed: false,
    tags: ["医疗"]
  },  {
    id: "ddw_dental_emr_template_kit",
    name: "ddw_dental_emr_template_kit",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "9 类口腔诊疗病历模板套件（YAML 配置驱动）",
    description: "9 类口腔诊疗病历模板套件（YAML 配置驱动）",
    version: "0.1.0",
    installed: false,
    tags: ["医疗"]
  },  {
    id: "ddw_dental_imaging",
    name: "ddw_dental_imaging",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "口腔影像管理",
    description: "口腔影像管理",
    version: "0.1.0",
    installed: false,
    tags: ["医疗"]
  },  {
    id: "ddw_dental_sterilization",
    name: "ddw_dental_sterilization",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "消毒追溯",
    description: "消毒追溯",
    version: "0.1.0",
    installed: false,
    tags: ["医疗"]
  },  {
    id: "ddw_doctor_schedule",
    name: "ddw_doctor_schedule",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "医生档案 + 排班管理（武汉东华口腔 14 医生）",
    description: "医生档案 + 排班管理（武汉东华口腔 14 医生）",
    version: "0.1.0",
    installed: false,
    tags: ["医疗"]
  },  {
    id: "ddw_informed_consent",
    name: "ddw_informed_consent",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "知情同意留痕",
    description: "知情同意留痕",
    version: "0.1.0",
    installed: false,
    tags: ["医疗"]
  },  {
    id: "ddw_patient_crm",
    name: "ddw_patient_crm",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "口腔门诊患者档案 CRM（基本信息/过敏史/标签/就诊记录）",
    description: "口腔门诊患者档案 CRM（基本信息/过敏史/标签/就诊记录）",
    version: "0.1.0",
    installed: false,
    tags: ["医疗"]
  },  {
    id: "ddw_talk_a1_asr",
    name: "ddw_talk_a1_asr",
    domain: "医疗健康",
    category: "通用",
    icon: "🏥",
    tagline: "钉钉 Talk A1 录音采集 + Whisper 转写（口腔门诊 ASR 入口）",
    description: "钉钉 Talk A1 录音采集 + Whisper 转写（口腔门诊 ASR 入口）",
    version: "0.1.0",
    installed: false,
    tags: ["医疗"]
  },
  // ========== 财务运营 ==========
  {
    id: "ddw_aggregated_pay",
    name: "ddw_aggregated_pay",
    domain: "财务运营",
    category: "通用",
    icon: "💰",
    tagline: "聚合支付与对账",
    description: "聚合支付与对账",
    version: "0.1.0",
    installed: false,
    tags: ["财务", "支付"]
  },  {
    id: "ddw_cost_knowledge",
    name: "ddw-cost-knowledge",
    domain: "财务运营",
    category: "通用",
    icon: "💰",
    tagline: "设计院历史造价文件 + 定额/清单/指标的统一管理：上传、LLM 提炼、自然语言检索、基于历史数据的…",
    description: "设计院历史造价文件 + 定额/清单/指标的统一管理：上传、LLM 提炼、自然语言检索、基于历史数据的造价估算与置信度评估。",
    version: "1.0.0",
    installed: false,
    tags: ["财务", "AI能力", "智能检索"]
  },  {
    id: "ddw_finance_dashboard",
    name: "ddw-finance-dashboard",
    domain: "财务运营",
    category: "通用",
    icon: "💰",
    tagline: "销售端 CRM 财务聚合查询插件。基于 P1-1 合同 / P1-3 应收 / P1-4 实收三张表…",
    description: "销售端 CRM 财务聚合查询插件。基于 P1-1 合同 / P1-3 应收 / P1-4 实收三张表的数据，提供财务仪表盘所需的统计指标：总览（合同金额 / 应收 / 实收 / 逾期）、逾期列表、最近",
    version: "1.0.0",
    installed: false,
    tags: ["财务"]
  },  {
    id: "ddw_invoice",
    name: "ddw-invoice",
    domain: "财务运营",
    category: "通用",
    icon: "💰",
    tagline: "销售端开票申请与发票记录：开票申请（requested）→ 上传发票文件（issued）→ 作废（v…",
    description: "销售端开票申请与发票记录：开票申请（requested）→ 上传发票文件（issued）→ 作废（voided）。支持专票/普票、价税分离（amount/tax_amount/total_amount",
    version: "1.0.0",
    installed: false,
    tags: ["财务"]
  },  {
    id: "ddw_payment",
    name: "ddw_payment",
    domain: "财务运营",
    category: "通用",
    icon: "💰",
    tagline: "收费与支付（多支付方式 + 日结汇总）",
    description: "收费与支付（多支付方式 + 日结汇总）",
    version: "0.1.0",
    installed: false,
    tags: ["财务", "支付"]
  },  {
    id: "ddw_reconciliation",
    name: "ddw-reconciliation",
    domain: "财务运营",
    category: "通用",
    icon: "💰",
    tagline: "销售端应收（Receivable）与实收（Payment）的核销（对账）插件。自动匹配推荐（金额+公…",
    description: "销售端应收（Receivable）与实收（Payment）的核销（对账）插件。自动匹配推荐（金额+公司精确匹配）、确认核销（事务：receivable.paid_amount + payment.ma",
    version: "1.0.0",
    installed: false,
    tags: ["财务"]
  },  {
    id: "ddw_saas_billing",
    name: "ddw-saas-billing",
    domain: "财务运营",
    category: "通用",
    icon: "💰",
    tagline: "订阅管理 + 用量计量 + 支付对接",
    description: "订阅管理 + 用量计量 + 支付对接",
    version: "0.1.0",
    installed: false,
    tags: ["财务", "支付"]
  },  {
    id: "ddw_wallet",
    name: "ddw_wallet",
    domain: "财务运营",
    category: "通用",
    icon: "💰",
    tagline: "DDW 预付费钱包插件 — 问渠 K12 学习 SaaS 的支付与计费底座",
    description: "DDW 预付费钱包插件 — 问渠 K12 学习 SaaS 的支付与计费底座",
    version: "0.1.0",
    installed: false,
    tags: ["财务", "支付"]
  },
  // ========== 知识培训 ==========
  {
    id: "ddw_bid_writer",
    name: "ddw-bid-writer",
    domain: "知识培训",
    category: "通用",
    icon: "📚",
    tagline: "设计院投标项目全流程：项目建档、标书自动生成、多风格修饰、标书审查、模板管理。",
    description: "设计院投标项目全流程：项目建档、标书自动生成、多风格修饰、标书审查、模板管理。",
    version: "1.0.0",
    installed: false,
    tags: ["知识库"]
  },  {
    id: "ddw_doc_assistant",
    name: "ddw-doc-assistant",
    domain: "知识培训",
    category: "通用",
    icon: "📚",
    tagline: "设计院/研究院文档知识助手 — 上传解析 · RAG问答 · 文档管理 · 混合检索",
    description: "设计院/研究院文档知识助手 — 上传解析 · RAG问答 · 文档管理 · 混合检索",
    version: "1.0.0",
    installed: false,
    tags: ["知识库", "智能检索"]
  },  {
    id: "ddw_ent_knowledge",
    name: "ddw-ent-knowledge",
    domain: "知识培训",
    category: "通用",
    icon: "📚",
    tagline: "企业知识库引擎 Flat KB MVP",
    description: "企业知识库引擎 Flat KB MVP",
    version: "1.0.0",
    installed: false,
    tags: ["知识库"]
  },  {
    id: "ddw_knowledge_hierarchy",
    name: "ddw-knowledge-hierarchy",
    domain: "知识培训",
    category: "通用",
    icon: "📚",
    tagline: "企业级层级知识检索引擎 — 多格式文档解析 + 层级索引 + 三阶段检索 + 文档生成",
    description: "企业级层级知识检索引擎 — 多格式文档解析 + 层级索引 + 三阶段检索 + 文档生成",
    version: "1.0.0",
    installed: false,
    tags: ["知识库", "智能检索"]
  },  {
    id: "ddw_training",
    name: "ddw-training",
    domain: "知识培训",
    category: "通用",
    icon: "📚",
    tagline: "苏格拉底教学法 + 多媒体课件 + 自动评估",
    description: "苏格拉底教学法 + 多媒体课件 + 自动评估",
    version: "0.1.0",
    installed: false,
    tags: ["知识库"]
  },  {
    id: "ddw_transcript_ai",
    name: "ddw-transcript-ai",
    domain: "知识培训",
    category: "通用",
    icon: "📚",
    tagline: "销售端录音/文本的 AI 处理插件。基于 DDW 内置 LLM Gateway 提供转写（模拟 AS…",
    description: "销售端录音/文本的 AI 处理插件。基于 DDW 内置 LLM Gateway 提供转写（模拟 ASR）、摘要、待办提取、关键实体抽取能力。无持久化、纯聚合 AI 能力。",
    version: "1.0.0",
    installed: false,
    tags: ["知识库", "AI能力"]
  },  {
    id: "ddw_wenqu_tutor",
    name: "DDW 问渠学科包（物理化学）",
    domain: "知识培训",
    category: "通用",
    icon: "📚",
    tagline: "苏格拉底式物理化学学习插件，支持错题本、家长统计等功能",
    description: "苏格拉底式物理化学学习插件，支持错题本、家长统计等功能",
    version: "0.1.0",
    installed: false,
    tags: ["知识库"]
  },
  // ========== 人力行政 ==========
  {
    id: "ddw_capa_workflow",
    name: "ddw-capa-workflow",
    domain: "人力行政",
    category: "通用",
    icon: "👥",
    tagline: "DDW CAPA工作流 — 纠正与预防措施全流程闭环管理",
    description: "DDW CAPA工作流 — 纠正与预防措施全流程闭环管理",
    version: "1.0.0",
    installed: false,
    tags: ["人事"]
  },  {
    id: "ddw_contract_core",
    name: "ddw-contract-core",
    domain: "人力行政",
    category: "通用",
    icon: "👥",
    tagline: "销售端合同全生命周期管理。自动生成单号 CT-YYYYMMDD-NNN；合同状态机 draft→pe…",
    description: "销售端合同全生命周期管理。自动生成单号 CT-YYYYMMDD-NNN；合同状态机 draft→pending_approval→approved→signed→active→completed/te",
    version: "1.0.0",
    installed: false,
    tags: ["人事", "状态机"]
  },  {
    id: "ddw_employee_roster",
    name: "ddw-employee-roster",
    domain: "人力行政",
    category: "通用",
    icon: "👥",
    tagline: "员工信息管理 + 培训档案",
    description: "员工信息管理 + 培训档案",
    version: "0.1.0",
    installed: false,
    tags: ["人事"]
  },  {
    id: "ddw_license_core",
    name: "ddw-license-core",
    domain: "人力行政",
    category: "通用",
    icon: "👥",
    tagline: "销售端许可证（License）全生命周期管理。许可证单号自动生成、状态机（active/expire…",
    description: "销售端许可证（License）全生命周期管理。许可证单号自动生成、状态机（active/expired/suspended/revoked/renewed）、自动过期检查、续费、暂停/恢复/吊销、插件",
    version: "1.0.0",
    installed: false,
    tags: ["人事", "状态机"]
  },  {
    id: "ddw_personnel_qual",
    name: "ddw-personnel-qual",
    domain: "人力行政",
    category: "通用",
    icon: "👥",
    tagline: "设计院人员证书（注册结构师/注册建筑师/高级工程师等）全生命周期管理：录入、查询、批量导入导出、到期…",
    description: "设计院人员证书（注册结构师/注册建筑师/高级工程师等）全生命周期管理：录入、查询、批量导入导出、到期预警、年检追踪、统计概览。",
    version: "1.0.0",
    installed: false,
    tags: ["人事"]
  },  {
    id: "ddw_position_designer",
    name: "ddw-position-designer",
    domain: "人力行政",
    category: "通用",
    icon: "👥",
    tagline: "DDW 岗位设计器插件 v1.0.0。 核心能力： 1) 4 维岗位设计（Outcome × 人的责…",
    description: "DDW 岗位设计器插件 v1.0.0。 核心能力： 1) 4 维岗位设计（Outcome × 人的责任 × Agent Stack × Decision Rights） 2) 5 因素加权决策路由引擎",
    version: "1.0.0",
    installed: false,
    tags: ["人事"]
  },
  // ========== 运营管理 ==========
  {
    id: "ddw_company_profile",
    name: "ddw-company-profile",
    domain: "运营管理",
    category: "通用",
    icon: "⚙️",
    tagline: "企业工商主数据管理。统一社会信用代码、营业执照、认证状态、开票信息；提供企业列表、详情、统计、联系人…",
    description: "企业工商主数据管理。统一社会信用代码、营业执照、认证状态、开票信息；提供企业列表、详情、统计、联系人关联等基础能力。",
    version: "1.0.0",
    installed: false,
    tags: ["运营", "合规审计"]
  },  {
    id: "ddw_flow_designer",
    name: "ddw-flow-designer",
    domain: "运营管理",
    category: "通用",
    icon: "⚙️",
    tagline: "零代码 DAG 流程设计器：拖拽编排数字员工与 Skill 协作流程，支持版本管理、跨部门审核、串行…",
    description: "零代码 DAG 流程设计器：拖拽编排数字员工与 Skill 协作流程，支持版本管理、跨部门审核、串行执行与公司级看板。",
    version: "1.0.0",
    installed: false,
    tags: ["运营", "数据报表"]
  },  {
    id: "ddw_instance_binding",
    name: "ddw-instance-binding",
    domain: "运营管理",
    category: "通用",
    icon: "⚙️",
    tagline: "销售端实例绑定（Instance Binding）：把客户企业 / 许可证与运行时实例（云端 Saa…",
    description: "销售端实例绑定（Instance Binding）：把客户企业 / 许可证与运行时实例（云端 SaaS 租户或本地 On-Premise 部署）建立关联。状态机 active/inactive/sus",
    version: "1.0.0",
    installed: false,
    tags: ["运营", "状态机"]
  },  {
    id: "ddw_inventory",
    name: "ddw_inventory",
    domain: "运营管理",
    category: "通用",
    icon: "⚙️",
    tagline: "耗材管理（库存/出入库/预警）",
    description: "耗材管理（库存/出入库/预警）",
    version: "0.1.0",
    installed: false,
    tags: ["运营"]
  },  {
    id: "ddw_kpi",
    name: "ddw-kpi",
    domain: "运营管理",
    category: "通用",
    icon: "⚙️",
    tagline: "培训成绩 → KPI 指标映射 + 绩效看板",
    description: "培训成绩 → KPI 指标映射 + 绩效看板",
    version: "0.1.0",
    installed: false,
    tags: ["运营", "数据报表"]
  },  {
    id: "ddw_kpi_dashboard",
    name: "ddw_kpi_dashboard",
    domain: "运营管理",
    category: "通用",
    icon: "⚙️",
    tagline: "KPI 与经营报表",
    description: "KPI 与经营报表",
    version: "0.1.0",
    installed: false,
    tags: ["运营", "数据报表"]
  },  {
    id: "ddw_marketing",
    name: "ddw_marketing",
    domain: "运营管理",
    category: "通用",
    icon: "⚙️",
    tagline: "营销通知",
    description: "营销通知",
    version: "0.1.0",
    installed: false,
    tags: ["运营"]
  },  {
    id: "ddw_support_ticket",
    name: "ddw-support-ticket",
    domain: "运营管理",
    category: "通用",
    icon: "⚙️",
    tagline: "销售端售后工单管理。客户报修、咨询、投诉、需求建议等工单的全生命周期管理；自动生成工单号 TKT-Y…",
    description: "销售端售后工单管理。客户报修、咨询、投诉、需求建议等工单的全生命周期管理；自动生成工单号 TKT-YYYYMMDD-NNN；状态机 open→in_progress→resolved→closed；与",
    version: "1.0.0",
    installed: false,
    tags: ["运营", "状态机"]
  },
  // ========== 平台能力 ==========
  {
    id: "ddw_authz",
    name: "ddw-authz",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "权限审计 RBAC + 操作审计日志",
    description: "权限审计 RBAC + 操作审计日志",
    version: "1.0.0",
    installed: false,
    tags: ["平台", "合规审计"]
  },  {
    id: "ddw_clarify",
    name: "ddw-clarify",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "对话反问澄清层",
    description: "对话反问澄清层",
    version: "1.0.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_llm_gateway_plugin",
    name: "ddw-llm-gateway",
    domain: "平台能力",
    category: "infrastructure",
    icon: "🔧",
    tagline: "LLM 统一网关插件 — 渠道管理、负载均衡、失败重试、流式转发",
    description: "LLM 统一网关插件 — 渠道管理、负载均衡、失败重试、流式转发",
    version: "1.0.0",
    installed: false,
    tags: ["平台", "AI能力"]
  },  {
    id: "ddw_memory",
    name: "ddw-memory",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "企业-部门-个人三层可裁剪记忆管理",
    description: "企业-部门-个人三层可裁剪记忆管理",
    version: "1.0.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_metric_dict",
    name: "ddw-metric-dict",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "指标口径管理",
    description: "指标口径管理",
    version: "0.1.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_org",
    name: "ddw-org",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "企业管理 11 个虚拟部门、数字员工、员工清单。预设种子数据（笑笑/法海/邮友等），支持 CRUD …",
    description: "企业管理 11 个虚拟部门、数字员工、员工清单。预设种子数据（笑笑/法海/邮友等），支持 CRUD 和 skill 分配。",
    version: "1.0.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_searxng",
    name: "ddw-searxng",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "SearXNG 元搜索引擎封装，提供聚合搜索与引擎健康检查能力。支持国内引擎，超时 15s，失败降级…",
    description: "SearXNG 元搜索引擎封装，提供聚合搜索与引擎健康检查能力。支持国内引擎，超时 15s，失败降级不影响底座。",
    version: "0.1.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_theme",
    name: "ddw-theme",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "界面主题系统（CSS变量注入）",
    description: "界面主题系统（CSS变量注入）",
    version: "0.1.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_token_entitlement",
    name: "ddw-token-entitlement",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "销售端客户企业 / 安装实例的 Token 额度分配、使用跟踪与超量控制。覆盖 platform/c…",
    description: "销售端客户企业 / 安装实例的 Token 额度分配、使用跟踪与超量控制。覆盖 platform/custom-key/local-llm 三类额度，支持分页筛选、消耗扣减、统计概览。",
    version: "1.0.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_token_manager_plugin",
    name: "ddw-token-manager",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "DDW AI Hub Token额度管理插件 — 预消费/后消费机制 + 校准反算 + 订阅感知路由",
    description: "DDW AI Hub Token额度管理插件 — 预消费/后消费机制 + 校准反算 + 订阅感知路由",
    version: "0.1.0",
    installed: false,
    tags: ["平台", "AI能力"]
  },  {
    id: "ddw_weaver",
    name: "ddw-weaver",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "泛微E9组织架构接入",
    description: "泛微E9组织架构接入",
    version: "0.1.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_website",
    name: "ddw-website",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "DDW 官网插件 — 主题模版/站点信息/页面清单统一管理，主题由底座后台切换",
    description: "DDW 官网插件 — 主题模版/站点信息/页面清单统一管理，主题由底座后台切换",
    version: "1.0.0",
    installed: false,
    tags: ["平台"]
  },  {
    id: "ddw_website_analytics",
    name: "ddw_website_analytics",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "网站访问/访客数据报表（解析 Caddy JSON access log）",
    description: "网站访问/访客数据报表（解析 Caddy JSON access log）",
    version: "0.1.0",
    installed: false,
    tags: ["平台", "数据报表"]
  },  {
    id: "ddw_wecom",
    name: "ddw-wecom",
    domain: "平台能力",
    category: "通用",
    icon: "🔧",
    tagline: "企业微信OAuth免登+JIT建号",
    description: "企业微信OAuth免登+JIT建号",
    version: "1.0.0",
    installed: false,
    tags: ["平台"]
  },
  // ========== 通用 ==========
  {
    id: "ddw_account_linker",
    name: "ddw-account-linker",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "销售端 CRM 账号映射中枢。将 DDW 客户企业映射到三种下游账号/租户/实例（user / sa…",
    description: "销售端 CRM 账号映射中枢。将 DDW 客户企业映射到三种下游账号/租户/实例（user / saas_tenant / on_premise_instance），支撑跨系统账号关联、唯一性校验、生",
    version: "1.0.0",
    installed: false,
    tags: ["通用"]
  },  {
    id: "ddw_ai_readiness",
    name: "ddw_ai_readiness",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "企业 AI 就绪度自评：问卷答案接收、服务端评分、商机分级（A/B/C）、销售端查询统计",
    description: "企业 AI 就绪度自评：问卷答案接收、服务端评分、商机分级（A/B/C）、销售端查询统计",
    version: "0.1.0",
    installed: false,
    tags: ["通用", "AI能力"]
  },  {
    id: "ddw_channel_auth",
    name: "ddw-channel-auth",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "DDW 渠道授权与结算插件 — 账号体系 + 客户报备状态机 + 注册码实例化 + 换码广播 + 电…",
    description: "DDW 渠道授权与结算插件 — 账号体系 + 客户报备状态机 + 注册码实例化 + 换码广播 + 电子签框架 + 试用 + POC 报告 + 一级分销红线",
    version: "1.0.0",
    installed: false,
    tags: ["通用", "状态机"]
  },  {
    id: "ddw_member_vip",
    name: "ddw_member_vip",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "会员储值与等级管理",
    description: "会员储值与等级管理",
    version: "0.1.0",
    installed: false,
    tags: ["通用"]
  },  {
    id: "ddw_online_cs",
    name: "ddw_online_cs",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "DDW 在线客服插件 — 官网联系我们页 AI 客服对话框后端。 基于官网知识库 RAG 检索 + …",
    description: "DDW 在线客服插件 — 官网联系我们页 AI 客服对话框后端。 基于官网知识库 RAG 检索 + 平台 LLM 网关生成回答， 复用平台 minimax→deepseek→ollama 兜底链路，无",
    version: "1.1.0",
    installed: false,
    tags: ["通用", "AI能力", "智能检索"]
  },  {
    id: "ddw_product_catalog",
    name: "ddw-product-catalog",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "销售端产品/插件目录主数据。DDW 自研产品（DDW 底座、DDW 插件、Token 套餐）与第三方…",
    description: "销售端产品/插件目录主数据。DDW 自研产品（DDW 底座、DDW 插件、Token 套餐）与第三方产品/服务统一管理：编码唯一、单价/单位/类型/版本控制，提供列表/详情/搜索/统计接口，供报价/订",
    version: "1.0.0",
    installed: false,
    tags: ["通用"]
  },  {
    id: "ddw_report",
    name: "ddw-report",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "订阅培训事件，生成学习进度报告和培训汇总",
    description: "订阅培训事件，生成学习进度报告和培训汇总",
    version: "0.1.0",
    installed: false,
    tags: ["通用"]
  },  {
    id: "ddw_signature_adapter",
    name: "ddw-signature-adapter",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "电子签章服务适配层。对接腾讯电子签 / 契约锁 / e签宝 / 人工签 等第三方电子签章服务商，管理…",
    description: "电子签章服务适配层。对接腾讯电子签 / 契约锁 / e签宝 / 人工签 等第三方电子签章服务商，管理签署请求生命周期（pending/signing/signed/rejected/expired），",
    version: "1.0.0",
    installed: false,
    tags: ["通用"]
  },  {
    id: "ddw_voice_capture",
    name: "ddw-voice-capture",
    domain: "通用",
    category: "通用",
    icon: "🌐",
    tagline: "销售端 CRM 录音管理插件。统一管理销售/客户经理在跟进过程中产生的多源录音（本地/电话/会议/随…",
    description: "销售端 CRM 录音管理插件。统一管理销售/客户经理在跟进过程中产生的多源录音（本地/电话/会议/随手记）元数据，支持与企业/联系人/商机建立可选关联，状态机由本插件维护（uploaded→trans",
    version: "1.0.0",
    installed: false,
    tags: ["通用", "状态机"]
  },
];
